### ISSUE TITLE
CORS error on loading main page

### ISSUE THREAD

**Issue by MrWindmark** [lydianlights/yet-another-factory-planner#18]
Hi, thx for your work. Find CORS error on loading main page. Add address to allowed in CORS politics pls. Ty
![CORS error](https://github.com/lydianlights/yet-another-factory-planner/assets/28528567/1df31ce6-864b-4480-b789-af959d02a91f)

**Comment by BennyExtreme** [comment]
It's not a CORS problem, the API is down, from yesterday.

**Comment by lunafoxfire** [comment]
Hello, the site should be working again. Very sorry for any down time. I had a configuration issue with my hosting service. Please let me know if there are any more uptime issues.

**Comment by dcelasun** [comment]
> Please let me know if there are any more uptime issues.

It seems to be down again:
![image](https://github.com/lydianlights/yet-another-factory-planner/assets/144373/8b3278c0-b678-4fe1-ab56-e171d94dbb07)

**Comment by MrWindmark** [comment]
![Screenshot from 2023-08-10 19-35-15](https://github.com/lydianlights/yet-another-factory-planner/assets/28528567/085cc4c3-d34a-4fe5-9294-6f667eadfc18)
Different error, but yes, server is down
