### ISSUE TITLE
bug: Search requires all lower case, should be case insensitive

### ISSUE THREAD

**Issue by highlyunavailable** [lydianlights/yet-another-factory-planner#2]
Searching for a recipe with an uppercase letter never finds anything even if it matches the case of the recipe:

![image](https://user-images.githubusercontent.com/6266125/144494772-0c13b9c2-88b0-4bc3-9992-383d443c5702.png)

Expected result:

Search is case insensitive and "STEEL", "steel", "Steel" and "sTEel" should all find the same recipes:

![image](https://user-images.githubusercontent.com/6266125/144494915-9aa126da-60cb-4e1a-bf5b-0c61d7c63675.png)

**Comment by lunafoxfire** [comment]
Oh haha thanks for reporting this, I will fix it as soon as possible
