### ISSUE TITLE
feature: Add underclock percent (and/or quantity, whichever is more precise) to the hover text for a component

### ISSUE THREAD

**Issue by highlyunavailable** [lydianlights/yet-another-factory-planner#4]
When making a build, it'd be nice to have underclocking added to the hover for a component.

Example:
![image](https://user-images.githubusercontent.com/6266125/144495389-43cfed6e-6e6a-411b-9683-4de84e8d11da.png)

Ideally the "quantity" calculation would be shown as well, e.g. `1 at 100% (5/min), 1 at 60% (3/min)` since a lot of times percentages are long and useless but the per-minute is a whole number - e.g. Concrete where 240 Limestone  = 5.33... constructors. In other words: `5 at 15/min and 1 at 5/min`, which is _much_ easier to comprehend.

**Comment by lunafoxfire** [comment]
Yep, this feature is planned in the nearby future and will likely come out at the same time as the ficsmas recipes!

**Comment by lunafoxfire** [comment]
This feature is now live!
