### ISSUE TITLE
feature: Add "rounding up" or "remainders" for components somehow

### ISSUE THREAD

**Issue by highlyunavailable** [lydianlights/yet-another-factory-planner#5]
Since I need components for a mall-style storage in every game of Satisfactory, I'd like to round up production if possible.

For example, given this example of "[2 Assemblers of Base Motor Recipe and 1 Assembler of Base Turbo Motor Recipe](https://www.satisfactory-planner.net/?f=v1_U5,40000000000000000000003fffffffffffffffffefffffffff,motor:motor_recipe:2|turbo_motor:turbo_motor_recipe:1,,70380:100:0|28860:243:0|52860:133:0|30900:227:0|11040:637:0|10500:670:0|6840:1028:0|11700:601:0|9780:719:0|2100:3351:0|12000:586:0|0:1:1,0,1000:5:30000)":

![image](https://user-images.githubusercontent.com/6266125/144496388-ed38c3d8-86ea-4c47-a63a-d120dc254056.png)

I want to be able to say "use the output of the 2 motor makers (7.5/min) to make Turbo Motors, and return the remainder (2.5/min) as an output to the plan" so the graph looks like this:

![image](https://user-images.githubusercontent.com/6266125/144496573-0b56eeeb-cf56-44b1-8dcb-cc645e53db33.png)

The same applies to this graph: I want to somehow tell the "Motors" node to "round up to 2 assemblers and output the extra":
![image](https://user-images.githubusercontent.com/6266125/144496695-7effa93d-f201-440f-806b-56fffd04cbe3.png)

**Comment by lunafoxfire** [comment]
I definitely see a usecase for a feature like this, since this is similar to how my roommate likes to design mall-type factories as you describe. Unfortunately due to the way the solver works this could be potentially somewhat complex to implement, as well as have nice UI for. I think it is potentially doable, but it probably won't be coming any time soon.

**Comment by lunafoxfire** [comment]
I'm marking this as closed, this is likely impossible due to the constraints of the Linear Programming algorithm I am using to solve factory layouts.
