### ISSUE TITLE
feature: Add extractor power consumption

### ISSUE THREAD

**Issue by highlyunavailable** [lydianlights/yet-another-factory-planner#6]
It'd be nice to have an idea of extractor power consumption. It's not an insignificant amount of usage, especially with Water Extractors and overclocked nodes and would be nice to have an "expected" number even if it overshoots slightly.

Estimation could assume extractors are always normal clocked: `(20MW * (water required that is not from waste like aluminum/120))` extractor count e.g. 10,000 water = `83.3...` extractors = `1,666.6...` MW of power and Miners... well they're weird. Maybe an OC percentage per resource in the Raw Resources screen? You could start with a Mk3 at 250% as "standard" estimation - it'll estimate high in most cases but at least it'd be accurate for big bases.

**Comment by lunafoxfire** [comment]
This feature should now be live! I've added a more in-depth breakdown of power in the reports tab.
