### ISSUE TITLE
Missing Assembly Director System

### ISSUE THREAD

**Issue by Duits** [lydianlights/yet-another-factory-planner#9]
As well as new Ammunition types

**Comment by lunafoxfire** [comment]
Hello, I cannot reproduce this issue. Here is an example factory with Assembly Director Systems:
https://www.satisfactory-planner.net/?factory=7bNMmQiB2Btat2yAL8ThQ

Be sure that you haven't turned off any recipes and that you have selected the latest game version (Update 7)
